#!/usr/bin/env bash

set -u

here="$(cd "$(dirname "$0")" && pwd)"
PATH="$here:$PATH"

export PROGRAM=ximeria
source "$here/prelude.bash"
source "$here/optparse.bash"

root_dir="${XIMERIA_ROOT:-$HOME/.ximeria}"
templates_dir="${XIMERIA_TEMPLATES_DIR:-$root_dir/templates}"

read -r -d '' spec <<EOF
program: "$PROGRAM"
opts:
  - help
  - version
args:
  - COMMAND
  - ...ARGS
types:
  COMMAND:
    - list
EOF

vals="$(echo "$spec" | optparse.parse "$@")"
res=$?

if (( res )); then
    >&2 echo
    echo "$spec" | optparse.display_usage
    exit 1
fi

eval "$vals"

if [[ -z ${command+x} ]]; then
    if [[ -n ${version+x} ]]; then
        echo "$VERSION"
        exit 0
    elif [[ -n ${help+x} ]]; then
        echo "$spec" | optparse.display_usage
        exit 0
    fi
    >&2 echo "command is missing"
    >&2 echo
    echo "$spec" | optparse.display_usage
    exit 1
fi

"$here/command/$command" "${args[@]}"
